export const CREATE_FRUIT = "CREATE_FRUIT";
export const RETRIEVE_FRUITS = "RETRIEVE_FRUITS";
export const UPDATE_FRUIT = "UPDATE_FRUIT";
export const DELETE_FRUIT = "DELETE_FRUIT";
export const DELETE_ALL_FRUITS = "DELETE_ALL_FRUITS";
